name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x'
      
      - name: Install dependencies and test
        run: |
          cd nadeo_event_api
          pip install -r requirements.txt
          export UBI_AUTH="${{secrets.UBI_AUTH}}"
          pytest
          pytest -m integration

      - name: Merge Master into Release branch
        if: success()
        run: |
          git fetch origin
          git checkout release
          git merge --no-ff master -m "Merging changes from master into release"
          git push origin release